### ISSUE TITLE
Snappy-java errors on ppc64le in multiple projects

### ISSUE THREAD

**Issue by sonia-garudi** [OpenPOWER-BigData/HDP-Flume#1]
Failed Projects: Flume NG Core,Flume NG HDFS Sink,Flume NG Kite Dataset Sink

Tests in error: 
test(org.apache.flume.serialization.TestSyslogAvroEventSerializer): [FAILED_TO_LOAD_NATIVE_LIBRARY] null
testAvroSerializerSnappyCompression(org.apache.flume.serialization.TestFlumeEventAvroEventSerializer): [FAILED_TO_LOAD_NATIVE_LIBRARY] null
testSnappyCompression(org.apache.flume.sink.hdfs.TestAvroEventSerializer): [FAILED_TO_LOAD_NATIVE_LIBRARY] null
testFileStore(org.apache.flume.sink.kite.TestDatasetSink): Could not initialize class org.xerial.snappy.Snappy
testPartitionedData(org.apache.flume.sink.kite.TestDatasetSink): Could not initialize class org.xerial.snappy.Snappy
testMiniClusterStore(org.apache.flume.sink.kite.TestDatasetSink): Could not initialize class org.xerial.snappy.Snappy
testBatchSize(org.apache.flume.sink.kite.TestDatasetSink): Could not initialize class org.xerial.snappy.Snappy
testTimedFileRolling(org.apache.flume.sink.kite.TestDatasetSink): Could not initialize class org.xerial.snappy.Snappy
testCompatibleSchemas(org.apache.flume.sink.kite.TestDatasetSink): Could not initialize class org.xerial.snappy.Snappy
testIncompatibleSchemas(org.apache.flume.sink.kite.TestDatasetSink): Could not initialize class org.xerial.snappy.Snappy
testMissingSchema(org.apache.flume.sink.kite.TestDatasetSink): Could not initialize class org.xerial.snappy.Snappy

RCA:
Flume downloads snappy-java 1.0.4.1 , which does not have ppc support.

**Comment by yussufsh** [comment]
work around is to add snappy-java:1.1.1 dependency to main pom.xml
